---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ambas empiezan con `function` seguido del nombre de la función
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ambas empiezan con `function` seguido de una llave
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ambas tienen un `return` en la primera línea
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ambas tienen un `return` en la anteúltima línea
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ambas terminan la primera línea con una llave
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ambas comienzan con mayúsculas
  checked: false
name: El juego de los parecidos
